services:
  mysql:
    image: mysql:8
    container_name: mesa_ayuda_mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mesa_ayuda
    ports:
      - "3306:3306"
    volumes:
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro

volumes:
  mysql_data: